#services:
#  test-db:
#    image: mysql:8.0.33
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=1111
#      - MYSQL_DATABASE=test
#    volumes:
#      - ./db-data:/var/lib/mysql
#    ports:
#      - 3306:3306