
version: '3.8'
services:
  springboot:
    container_name: user_registration_back_end_cnt
    image: sainaveen12/user_registration_back_end_docker:latest
    ports:
      - 8080:8080
  mysql:
    container_name: sqldb_cnt
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=18181818
      - MYSQL_USER=root
      - MYSQL_PASSWORD=18181818
      - MYSQL_DATABASE=user_reg_db_ec2_docker
    volumes:
      - appvolume:/var/lib/mysql
volumes:
  appvolume:



#version: "3.8"
#
#services:
#  mysqldb:
#    image: mysql:8.0.33
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#    build: ./user-app
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#
#volumes:
#  db:

