
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: saipostgres
      POSTGRES_PASSWORD: 18181818
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

#version: '3.8'
#
#services:
#  mysql-cnt:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=18181818
#      - MYSQL_DATABASE=user_sql_ec2_docker
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=18181818
#    volumes:
#      - /data/mysql
#  springboot-docker-compose-mysql-app-container:
#    image: sainaveen12/user_registration_back_end_docker:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-cnt
#    volumes:
#      - /data/springboot-docker-compose-mysql-app


#version: "3.8"
#
#services:
#  mysqldb:
#    image: mysql:8.0.33
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#    build: ./user-app
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#
#volumes:
#  db:
#
