spring:
  datasource:
    username: sainaveen
    url: jdbc:h2:mem:userregistration_db_h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    password: ${H2_DB_PSD}
  h2:
    console:
      enabled: 'true'
      settings:
        web-allow-others: 'true'
        trace: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

