name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login
      - name: Build docker image
        run: docker build -t psainaveen12/user_registration_back_end .
      - name: Publish image to docker hub
        run: docker push psainaveen12/user_registration_back_end:latest

  deploy:
    needs: build
    runs-on: aws-ec2-docker
    steps:
      - name: Pull Image from docker hub
        run: docker pull psainaveen12/user_registration_back_end:latest
      - name: Delete old container
        run: docker rm -f user_registration_back_end-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name user_registration_back_end-container psainaveen12/user_registration_back_end
