name: Docker CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u $USERNAME_DOCKER -p $PASSWORD_DOCKER
        env:
            USERNAME_DOCKER: ${{secrets.USERNAME_DOCKER}}
            PASSWORD_DOCKER: ${{secrets.PASSWORD_DOCKER}}
      - name: Build docker image
        run: docker build -t sainaveen12/user_registration_back_end_docker .
      - name: Publish image to docker hub
        run: docker push sainaveen12/user_registration_back_end_docker:latest

  deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Delete old container
          run: sudo docker rm -f user_registration_back_end_cnt || true
        - name: Delete old image
          run: sudo docker rmi -f sainaveen12/user_registration_back_end_docker:latest
        - name: Pull Image from docker hub
          run: sudo docker pull sainaveen12/user_registration_back_end_docker:latest
        - name: Kill port 8080
          run: sudo fuser -n tcp -k 8080 || true
        - name: Run docker container
          run: sudo docker run -d -p 8080:8080 --name user_registration_back_end_cnt sainaveen12/user_registration_back_end_docker
